// -------------------------------------------------------------
// 
// File Name: C:\Course_Material\UofT\ECE1718\assignment2\Simulink\MAC_int_code_gen\MAC_single\HDL_DUT.v
// Created: 2023-03-09 14:54:03
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// out                           ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HDL_DUT
// Source Path: MAC_single/HDL_DUT
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HDL_DUT
          (clk,
           reset,
           clk_enable,
           in1,
           in2,
           ce_out,
           out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [31:0] in1;  // int32
  input   signed [31:0] in2;  // int32
  output  ce_out;
  output  signed [64:0] out;  // sfix65


  wire enb;
  wire signed [63:0] Dot_Product_out1;  // sfix64
  reg signed [64:0] Memory_out1;  // sfix65
  wire signed [31:0] Data_Type_Conversion_out1;  // int32
  wire signed [64:0] Add_1;  // sfix65
  wire signed [64:0] Add_2;  // sfix65
  wire signed [64:0] Add_out1;  // sfix65


  assign Dot_Product_out1 = in1 * in2;



  assign enb = clk_enable;

  assign Data_Type_Conversion_out1 = Memory_out1[31:0];



  assign Add_1 = {Dot_Product_out1[63], Dot_Product_out1};
  assign Add_2 = {{33{Data_Type_Conversion_out1[31]}}, Data_Type_Conversion_out1};
  assign Add_out1 = Add_1 + Add_2;



  always @(posedge clk or posedge reset)
    begin : Memory_process
      if (reset == 1'b1) begin
        Memory_out1 <= 65'sh00000000000000000;
      end
      else begin
        if (enb) begin
          Memory_out1 <= Add_out1;
        end
      end
    end



  assign out = Memory_out1;

  assign ce_out = clk_enable;

endmodule  // HDL_DUT

