// -------------------------------------------------------------
// 
// File Name: C:\Course_Material\UofT\ECE1718\assignment2\Simulink\MAC_blfoat16_code_gen\MAC_single\HDL_DUT.v
// Created: 2023-03-09 14:56:48
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// out                           ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HDL_DUT
// Source Path: MAC_single/HDL_DUT
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HDL_DUT
          (clk,
           reset,
           clk_enable,
           in1,
           in2,
           ce_out,
           out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [15:0] in1;  // uint16
  input   [15:0] in2;  // uint16
  output  ce_out;
  output  [32:0] out;  // ufix33


  wire enb;
  wire [15:0] Dot_Product_out1;  // uint32
  reg [15:0] Memory_out1;  // ufix33
  wire [15:0] Data_Type_Conversion_out1;  // uint32
  wire [15:0] Add_1;  // ufix33
  wire [15:0] Add_2;  // ufix33
  wire [15:0] Add_out1;  // ufix33


  multiplier_bfloat16 multiplier(
    .n1(in1),
    .n2(in2),
    .res(Dot_Product_out1),
    .Overflow(),
    .Underflow(),
    .Exception()
  );


  assign enb = clk_enable;

  assign Data_Type_Conversion_out1 = Memory_out1[15:0];



  assign Add_1 = Dot_Product_out1;
  assign Add_2 = Data_Type_Conversion_out1;
  
  adder_bfloat16 adder(
    .n1(Add_1),
    .n2(Add_2),
    .res(Add_out1),
    .Overflow(),
    .Underflow(),
    .Exception()
  );


  always @(posedge clk or posedge reset)
    begin : Memory_process
      if (reset == 1'b1) begin
        Memory_out1 <= 33'h000000000;
      end
      else begin
        if (enb) begin
          Memory_out1 <= Add_out1;
        end
      end
    end



  assign out = Memory_out1;

  assign ce_out = clk_enable;

endmodule  // HDL_DUT

